change shell scripts

diff --git a/tools/shell/build-codepen b/tools/shell/build-codepen
--- a/tools/shell/build-codepen
+++ b/tools/shell/build-codepen
@@ -1,6 +1,5 @@
 #!/bin/bash
 
-
 SRC_DIR='apps/webaudio-spectrum-analyser/src'
 
 DIST_DIR='dist/codepen'
@@ -8,33 +7,35 @@ DIST_HTML="${DIST_DIR}/index.html"
 DIST_CSS="${DIST_DIR}/style.scss"
 DIST_TS="${DIST_DIR}/script.ts"
 
-
-cd "$(dirname "${BASH_SOURCE[0]}")"
-cd ../..
-
+cd "$(dirname "${BASH_SOURCE[0]}")/../.."
+source tools/shell/common.sh
 
 [[ -e $DIST_DIR ]] && rm -rfv "${DIST_DIR}/*"
-mkdir -pv "$DIST_DIR" || exit 1
+mkdir -pv "$DIST_DIR" || error 'mkdir failed'
 
-echo 'building html...' >&2
-exec 3>"$DIST_HTML" || exit 1
-echo '<webaudio-spectrum-analyser-root></webaudio-spectrum-analyser-root>' >&3 \
-  || exit 1
+log 'building html...'
+
+exec 3>"$DIST_HTML" || error "could not open '${DIST_HTML}'"
+echo '<app-root></app-root>' >&3 || error "could not write '${DIST_HTML}'"
 while read path; do
   id="$(basename $path)"
   echo -e "\\n\\n<script type=\"text/ng-template\" id=\"${id}\">" >&3 \
     && cat "$path" >&3 \
     && echo '</script>' >&3 \
-    || exit 1
+    || error "could not add '${path}' to '${DIST_HTML}'"
 done < <(find "${SRC_DIR}" -iname '*.component.html');
-exec 3>&- || exit 1
+exec 3>&- || error "could not close '${DIST_HTML}'"
 
-echo 'building css...' >&2
-cat "${SRC_DIR}/css/"{_vars,vendor,styles}".scss" \
-  | egrep -v '^\s*@import' >"$DIST_CSS" \
-  || exit 1
+log 'building css...'
 
-echo 'building ts...' >&2
+egrep \
+  -hv '^\s*@import' \
+  "${SRC_DIR}/css/"{_vars,vendor,styles}".scss" \
+  >"$DIST_CSS" \
+  || error 'css build failed'
+
+log 'building ts...'
+
 find "$SRC_DIR" \
      -iname '*.ts' \
      -not -iname '*.spec.ts' \
@@ -42,4 +43,4 @@ find "$SRC_DIR" \
      -not -iname '*.prod.ts' \
      -not -iname 'polyfills.ts' \
   | xargs ./tools/shell/ts-concat ./tools/shell/modules.json >"$DIST_TS" \
-  || exit 1
+  || error 'ts build failed'
